/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepoIdIndexRouteImport } from './routes/$repoId/index'
import { Route as RepoIdPullNumberRouteImport } from './routes/$repoId/$pullNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoIdIndexRoute = RepoIdIndexRouteImport.update({
  id: '/$repoId/',
  path: '/$repoId/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoIdPullNumberRoute = RepoIdPullNumberRouteImport.update({
  id: '/$repoId/$pullNumber',
  path: '/$repoId/$pullNumber',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$repoId/$pullNumber': typeof RepoIdPullNumberRoute
  '/$repoId': typeof RepoIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$repoId/$pullNumber': typeof RepoIdPullNumberRoute
  '/$repoId': typeof RepoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$repoId/$pullNumber': typeof RepoIdPullNumberRoute
  '/$repoId/': typeof RepoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$repoId/$pullNumber' | '/$repoId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$repoId/$pullNumber' | '/$repoId'
  id: '__root__' | '/' | '/$repoId/$pullNumber' | '/$repoId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RepoIdPullNumberRoute: typeof RepoIdPullNumberRoute
  RepoIdIndexRoute: typeof RepoIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$repoId/': {
      id: '/$repoId/'
      path: '/$repoId'
      fullPath: '/$repoId'
      preLoaderRoute: typeof RepoIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$repoId/$pullNumber': {
      id: '/$repoId/$pullNumber'
      path: '/$repoId/$pullNumber'
      fullPath: '/$repoId/$pullNumber'
      preLoaderRoute: typeof RepoIdPullNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RepoIdPullNumberRoute: RepoIdPullNumberRoute,
  RepoIdIndexRoute: RepoIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
